# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jens Weber
title: Enterprise Architect & Software Guru
email: github@weltie.dev
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jweberde
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jensweberfounder
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-jw.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jens and I'm a Lead Enterprise Architect with a fable for great code & good design. I love to see people using my products and spent most of my time developing B2C or B2E applications.

  I am an agile enthusiast living by the principal: "Individuals and interactions over processes and tools"

  Development Skills:
  - Java
  - Angular / React
  - NodeJs
  - JavaScript / TypeScript
  - Go
  - Docker / Kubernetes
  - Opensearch / Elasticsearch, Neo4j, MySQL, PostgreSQL, TimeScale DB
  - ActiveMQ Artemis, Kafka

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: StealthProject
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Making sales teams more successful.
        description: | # this will include new lines to allow paragraphs
          Stay tuned, working on something big and can't wait to share ones it's ready. Meanwhile... Look at that beautiful picture.

          ![Trees](/images/landscape-mountain.jpg "Trees")
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Retarus
        link: https://retarus.com
        link_text: retarus.com
        sub_title: Lead Enterprise Architect
        caption: Feb 2017 - Present
        #quote: >
        #    Responsible for the Enterprise API Program guiding the Product-Centric Organization towards the concept of API-as-a-Product.
        description: | # this will include new lines to allow paragraphs
            Responsible for the Enterprise API Program guiding the Product-Centric Organization towards the concept of API-as-a-Product.

            Establishing standards and best-practices to improve our Multi-Region Application Architecture with focus on Data Protection and Security.
            Working on the platform to enable development teams to effectively contribute to the Enterprise API Program via Technology, Trainings and Knowledge Transfer.

            I als worked as Product Line Manager for UI/UX & Platform and as Senior Software Developer for retarus.
      - layout: left
        title: Campus-Compass
        link: https://campus-compass.eu
        link_text: campus-compass.eu
        sub_title: CTO & Co-Founder
        caption: Nov 2013 - Dec 2015 (full-time)
        description: | # this will include new lines to allow paragraphs
            We from Campus-Compass.eu know from experience how hard the choice of a suitable study path is. Hence we offer you the best sources of information: Ask a student point-blank, look at detailed employee’s backgrounds and profit from professional advice!
      - layout: left
        title: Experteer
        link: https://experteer.com
        link_text: experteer.com
        sub_title: Intrapreneur
        caption: Aug 2011 - Jan 2014
        description: | # this will include new lines to allow paragraphs
          Responsible for the development of emplido.com as an Experteer service, including product- and brand-strategy. Implementation of the software architecture and infrastructure.

          Responsible for the strategy and development of mystrengths360.com including market research, product strategy and technical development of software architecture and infrastructure.

          Development and support of Experteer`s social strategy. 
      - layout: left
        title: Emplido
        sub_title: CTO & Co-Founder
        caption: 2010 - Jul 2011 (sold)
        description: | # this will include new lines to allow paragraphs
            Emplido is the place to go to empower your strengths, network and professional influence. We socialize your career so you can become a better professional. With Emplido you discover your strengths, see what others think about you, identify the movers and shakers in your network, and share your professional reputation on your social networks. Career success starts with you. At Emplido you find out more about yourself and your network.

            Acquired by German mid-size player Experteer GmbH achieving over 50 times ROI
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Munich
        caption: 2006 - 2011
        sub_title: MSc & BSc Information Systems
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          People keep asking me: Why did you study Information System and not Computer Science. The answer is simple I love to see things in context. I was never only interested in one small component of a large applications.
          I wanted to be able to understand the whole thing.

          After talking to Head of Development, CTO's and CIO's during my internships, I was able to find my path. When I started university I already had a lot of development experience, which helped me a lot.
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    I love technology and wrapping my mind around complex problems other than that
  #    - Rock climbing
  #    - Gaming
  #     - Knitting
 #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
 #
 #     Look at this cool image  
 #     ![Trees](/images/landscape-mountain.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
